In [53]:
# Imports
import math
import numpy as np
import pandas as pd
import geopandas as gpd
from shapely import wkt
import os
import shapefile
from geopy.distance import geodesic

# !pip install geocoder
from geopy.geocoders import Nominatim

In [4]:
# Files
businesses = pd.read_csv('data/businesses.csv', delimiter=';')
businesses.head()

,WKT,ADDRESS,OPEN YEAR,OPEN MONTH,TYPE,Description,Merchandise Type
0,POINT (1396322.217 4990301.69),VIA CLAUDIO LUIGI BERTHOLLET 24,1977,1,EXTRALIMENTARI,PICCOLE STRUTTURE,Extralimentari
1,POINT (1396322.217 4990301.69),VIA CLAUDIO LUIGI BERTHOLLET 24,1985,6,ALIMENTARI,PICCOLE STRUTTURE,Panificio
2,POINT (1396303.762 4990325.001),VIA CLAUDIO LUIGI BERTHOLLET 25/F,2017,9,ALTRO,DIA di somministrazione,Nessuna
3,POINT (1396434.395 4990540.6),CORSO VITTORIO EMANUELE II 21/A,2013,10,ALTRO,DIA di somministrazione,Nessuna
4,POINT (1396434.395 4990540.6),CORSO VITTORIO EMANUELE II 21/A,2009,2,ALTRO,DIA di somministrazione,Nessuna

In [5]:
businesses['WKT_proc'] = businesses['WKT'].apply(wkt.loads)
businesses

,WKT,ADDRESS,OPEN YEAR,OPEN MONTH,TYPE,Description,Merchandise Type,WKT_proc
0,POINT (1396322.217 4990301.69),VIA CLAUDIO LUIGI BERTHOLLET 24,1977,1,EXTRALIMENTARI,PICCOLE STRUTTURE,Extralimentari,POINT (1396322.217 4990301.69)
1,POINT (1396322.217 4990301.69),VIA CLAUDIO LUIGI BERTHOLLET 24,1985,6,ALIMENTARI,PICCOLE STRUTTURE,Panificio,POINT (1396322.217 4990301.69)
2,POINT (1396303.762 4990325.001),VIA CLAUDIO LUIGI BERTHOLLET 25/F,2017,9,ALTRO,DIA di somministrazione,Nessuna,POINT (1396303.762 4990325.001)
3,POINT (1396434.395 4990540.6),CORSO VITTORIO EMANUELE II 21/A,2013,10,ALTRO,DIA di somministrazione,Nessuna,POINT (1396434.395 4990540.6)
4,POINT (1396434.395 4990540.6),CORSO VITTORIO EMANUELE II 21/A,2009,2,ALTRO,DIA di somministrazione,Nessuna,POINT (1396434.395 4990540.6)
...,...,...,...,...,...,...,...,...
823,POINT (1396561.148 4990473.514),CORSO VITTORIO EMANUELE II 9,2016,9,ALIMENTARI,PICCOLE STRUTTURE,217,POINT (1396561.148 4990473.514)
824,POINT (1396561.148 4990473.514),CORSO VITTORIO EMANUELE II 9,2016,7,EXTRALIMENTARI,PICCOLE STRUTTURE,208,POINT (1396561.148 4990473.514)
825,POINT (1396561.148 4990473.514),CORSO VITTORIO EMANUELE II 9,1993,4,EXTRALIMENTARI,PICCOLE STRUTTURE,Extralimentari,POINT (1396561.148 4990473.514)
826,POINT (1396319.554 4990303.098),VIA CLAUDIO LUIGI BERTHOLLET 24/C,2001,12,EXTRALIMENTARI,PICCOLE STRUTTURE,Abbigliamento,POINT (1396319.554 4990303.098)
827,POINT (1396322.217 4990301.69),VIA CLAUDIO LUIGI BERTHOLLET 24,2008,7,ALTRO,Somministrazione,Nessuna,POINT (1396322.217 4990301.69)

In [7]:
gdf = gpd.GeoDataFrame(businesses, geometry='WKT_proc')
gdf

,WKT,ADDRESS,OPEN YEAR,OPEN MONTH,TYPE,Description,Merchandise Type,WKT_proc
0,POINT (1396322.217 4990301.69),VIA CLAUDIO LUIGI BERTHOLLET 24,1977,1,EXTRALIMENTARI,PICCOLE STRUTTURE,Extralimentari,POINT (1396322.217 4990301.690)
1,POINT (1396322.217 4990301.69),VIA CLAUDIO LUIGI BERTHOLLET 24,1985,6,ALIMENTARI,PICCOLE STRUTTURE,Panificio,POINT (1396322.217 4990301.690)
2,POINT (1396303.762 4990325.001),VIA CLAUDIO LUIGI BERTHOLLET 25/F,2017,9,ALTRO,DIA di somministrazione,Nessuna,POINT (1396303.762 4990325.001)
3,POINT (1396434.395 4990540.6),CORSO VITTORIO EMANUELE II 21/A,2013,10,ALTRO,DIA di somministrazione,Nessuna,POINT (1396434.395 4990540.600)
4,POINT (1396434.395 4990540.6),CORSO VITTORIO EMANUELE II 21/A,2009,2,ALTRO,DIA di somministrazione,Nessuna,POINT (1396434.395 4990540.600)
...,...,...,...,...,...,...,...,...
823,POINT (1396561.148 4990473.514),CORSO VITTORIO EMANUELE II 9,2016,9,ALIMENTARI,PICCOLE STRUTTURE,217,POINT (1396561.148 4990473.514)
824,POINT (1396561.148 4990473.514),CORSO VITTORIO EMANUELE II 9,2016,7,EXTRALIMENTARI,PICCOLE STRUTTURE,208,POINT (1396561.148 4990473.514)
825,POINT (1396561.148 4990473.514),CORSO VITTORIO EMANUELE II 9,1993,4,EXTRALIMENTARI,PICCOLE STRUTTURE,Extralimentari,POINT (1396561.148 4990473.514)
826,POINT (1396319.554 4990303.098),VIA CLAUDIO LUIGI BERTHOLLET 24/C,2001,12,EXTRALIMENTARI,PICCOLE STRUTTURE,Abbigliamento,POINT (1396319.554 4990303.098)
827,POINT (1396322.217 4990301.69),VIA CLAUDIO LUIGI BERTHOLLET 24,2008,7,ALTRO,Somministrazione,Nessuna,POINT (1396322.217 4990301.690)

In [21]:
gdf["WKT_X"] = gdf.geometry.x
gdf["WKT_Y"] = gdf.geometry.y

gdf

,WKT,ADDRESS,OPEN YEAR,OPEN MONTH,TYPE,Description,Merchandise Type,WKT_proc,lat,long,WKT_X,WKT_Y
0,POINT (1396322.217 4990301.69),VIA CLAUDIO LUIGI BERTHOLLET 24,1977,1,EXTRALIMENTARI,PICCOLE STRUTTURE,Extralimentari,POINT (1396322.217 4990301.690),1396322.217,4990301.690,1396322.217,4990301.690
1,POINT (1396322.217 4990301.69),VIA CLAUDIO LUIGI BERTHOLLET 24,1985,6,ALIMENTARI,PICCOLE STRUTTURE,Panificio,POINT (1396322.217 4990301.690),1396322.217,4990301.690,1396322.217,4990301.690
2,POINT (1396303.762 4990325.001),VIA CLAUDIO LUIGI BERTHOLLET 25/F,2017,9,ALTRO,DIA di somministrazione,Nessuna,POINT (1396303.762 4990325.001),1396303.762,4990325.001,1396303.762,4990325.001
3,POINT (1396434.395 4990540.6),CORSO VITTORIO EMANUELE II 21/A,2013,10,ALTRO,DIA di somministrazione,Nessuna,POINT (1396434.395 4990540.600),1396434.395,4990540.600,1396434.395,4990540.600
4,POINT (1396434.395 4990540.6),CORSO VITTORIO EMANUELE II 21/A,2009,2,ALTRO,DIA di somministrazione,Nessuna,POINT (1396434.395 4990540.600),1396434.395,4990540.600,1396434.395,4990540.600
...,...,...,...,...,...,...,...,...,...,...,...,...
823,POINT (1396561.148 4990473.514),CORSO VITTORIO EMANUELE II 9,2016,9,ALIMENTARI,PICCOLE STRUTTURE,217,POINT (1396561.148 4990473.514),1396561.148,4990473.514,1396561.148,4990473.514
824,POINT (1396561.148 4990473.514),CORSO VITTORIO EMANUELE II 9,2016,7,EXTRALIMENTARI,PICCOLE STRUTTURE,208,POINT (1396561.148 4990473.514),1396561.148,4990473.514,1396561.148,4990473.514
825,POINT (1396561.148 4990473.514),CORSO VITTORIO EMANUELE II 9,1993,4,EXTRALIMENTARI,PICCOLE STRUTTURE,Extralimentari,POINT (1396561.148 4990473.514),1396561.148,4990473.514,1396561.148,4990473.514
826,POINT (1396319.554 4990303.098),VIA CLAUDIO LUIGI BERTHOLLET 24/C,2001,12,EXTRALIMENTARI,PICCOLE STRUTTURE,Abbigliamento,POINT (1396319.554 4990303.098),1396319.554,4990303.098,1396319.554,4990303.098
827,POINT (1396322.217 4990301.69),VIA CLAUDIO LUIGI BERTHOLLET 24,2008,7,ALTRO,Somministrazione,Nessuna,POINT (1396322.217 4990301.690),1396322.217,4990301.690,1396322.217,4990301.690

In [37]:
# Create a Geolocator
geolocator = Nominatim(user_agent="wdl-tech-moguls")

# Note Google Maps reads (lat, long)
# iterate through each row and select 
# 'Name' and 'Age' column respectively.
for i in range(len(gdf)):
    location = geolocator.geocode(gdf.loc[i, "ADDRESS"])
    gdf.loc[i, "Longitude"], gdf.loc[i, "Latitude"] = location.longitude, location.latitude

gdf

,WKT,ADDRESS,OPEN YEAR,OPEN MONTH,TYPE,Description,Merchandise Type,WKT_proc,lat,long,WKT_X,WKT_Y,Longitude,Latitude
0,POINT (1396322.217 4990301.69),VIA CLAUDIO LUIGI BERTHOLLET 24,1977,1,EXTRALIMENTARI,PICCOLE STRUTTURE,Extralimentari,POINT (1396322.217 4990301.690),1396322.217,4990301.690,1396322.217,4990301.690,7.682778,45.058444
1,POINT (1396322.217 4990301.69),VIA CLAUDIO LUIGI BERTHOLLET 24,1985,6,ALIMENTARI,PICCOLE STRUTTURE,Panificio,POINT (1396322.217 4990301.690),1396322.217,4990301.690,1396322.217,4990301.690,7.682778,45.058444
2,POINT (1396303.762 4990325.001),VIA CLAUDIO LUIGI BERTHOLLET 25/F,2017,9,ALTRO,DIA di somministrazione,Nessuna,POINT (1396303.762 4990325.001),1396303.762,4990325.001,1396303.762,4990325.001,7.682632,45.058607
3,POINT (1396434.395 4990540.6),CORSO VITTORIO EMANUELE II 21/A,2013,10,ALTRO,DIA di somministrazione,Nessuna,POINT (1396434.395 4990540.600),1396434.395,4990540.600,1396434.395,4990540.600,7.684246,45.060567
4,POINT (1396434.395 4990540.6),CORSO VITTORIO EMANUELE II 21/A,2009,2,ALTRO,DIA di somministrazione,Nessuna,POINT (1396434.395 4990540.600),1396434.395,4990540.600,1396434.395,4990540.600,7.684246,45.060567
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
823,POINT (1396561.148 4990473.514),CORSO VITTORIO EMANUELE II 9,2016,9,ALIMENTARI,PICCOLE STRUTTURE,217,POINT (1396561.148 4990473.514),1396561.148,4990473.514,1396561.148,4990473.514,8.401330,40.837933
824,POINT (1396561.148 4990473.514),CORSO VITTORIO EMANUELE II 9,2016,7,EXTRALIMENTARI,PICCOLE STRUTTURE,208,POINT (1396561.148 4990473.514),1396561.148,4990473.514,1396561.148,4990473.514,8.401330,40.837933
825,POINT (1396561.148 4990473.514),CORSO VITTORIO EMANUELE II 9,1993,4,EXTRALIMENTARI,PICCOLE STRUTTURE,Extralimentari,POINT (1396561.148 4990473.514),1396561.148,4990473.514,1396561.148,4990473.514,8.401330,40.837933
826,POINT (1396319.554 4990303.098),VIA CLAUDIO LUIGI BERTHOLLET 24/C,2001,12,EXTRALIMENTARI,PICCOLE STRUTTURE,Abbigliamento,POINT (1396319.554 4990303.098),1396319.554,4990303.098,1396319.554,4990303.098,7.682837,45.058413
827,POINT (1396322.217 4990301.69),VIA CLAUDIO LUIGI BERTHOLLET 24,2008,7,ALTRO,Somministrazione,Nessuna,POINT (1396322.217 4990301.690),1396322.217,4990301.690,1396322.217,4990301.690,7.682778,45.058444

In [39]:
final_businesses = gdf.copy()[["WKT", "ADDRESS","OPEN YEAR", "OPEN MONTH", "TYPE", "Description", "Merchandise Type", "Longitude", "Latitude"]]
final_businesses

,WKT,ADDRESS,OPEN YEAR,OPEN MONTH,TYPE,Description,Merchandise Type,Longitude,Latitude
0,POINT (1396322.217 4990301.69),VIA CLAUDIO LUIGI BERTHOLLET 24,1977,1,EXTRALIMENTARI,PICCOLE STRUTTURE,Extralimentari,7.682778,45.058444
1,POINT (1396322.217 4990301.69),VIA CLAUDIO LUIGI BERTHOLLET 24,1985,6,ALIMENTARI,PICCOLE STRUTTURE,Panificio,7.682778,45.058444
2,POINT (1396303.762 4990325.001),VIA CLAUDIO LUIGI BERTHOLLET 25/F,2017,9,ALTRO,DIA di somministrazione,Nessuna,7.682632,45.058607
3,POINT (1396434.395 4990540.6),CORSO VITTORIO EMANUELE II 21/A,2013,10,ALTRO,DIA di somministrazione,Nessuna,7.684246,45.060567
4,POINT (1396434.395 4990540.6),CORSO VITTORIO EMANUELE II 21/A,2009,2,ALTRO,DIA di somministrazione,Nessuna,7.684246,45.060567
...,...,...,...,...,...,...,...,...,...
823,POINT (1396561.148 4990473.514),CORSO VITTORIO EMANUELE II 9,2016,9,ALIMENTARI,PICCOLE STRUTTURE,217,8.401330,40.837933
824,POINT (1396561.148 4990473.514),CORSO VITTORIO EMANUELE II 9,2016,7,EXTRALIMENTARI,PICCOLE STRUTTURE,208,8.401330,40.837933
825,POINT (1396561.148 4990473.514),CORSO VITTORIO EMANUELE II 9,1993,4,EXTRALIMENTARI,PICCOLE STRUTTURE,Extralimentari,8.401330,40.837933
826,POINT (1396319.554 4990303.098),VIA CLAUDIO LUIGI BERTHOLLET 24/C,2001,12,EXTRALIMENTARI,PICCOLE STRUTTURE,Abbigliamento,7.682837,45.058413
827,POINT (1396322.217 4990301.69),VIA CLAUDIO LUIGI BERTHOLLET 24,2008,7,ALTRO,Somministrazione,Nessuna,7.682778,45.058444

In [40]:
# Save into CSV
final_businesses.to_csv("data/businesses_proc.csv")

In [58]:
# Function that calculates the distance in km between two points using the latitude and longitude data 
def get_lat_lon_dist(row):
    
    latlon1 = tuple(row[['latitude1', 'longitude1']])
    latlon2 = tuple(row[['latitude2', 'longitude2']])

    return geodesic(latlon1, latlon2).kilometers



def compute_distances(df_pois, data_entities):

    # In order to be able to apply the function defined above with the data from the file with the points of interest, 
    data_entities[['latitude', 'longitude']] = data_entities[["Lat", "Long"]]
    df_pois[['latitude', 'longitude']] = df_pois[["Latitude", "Longitude"]]
    

    # Cross-join to get all combinations of latitude/longitude
    dist = pd.merge(data_entities.copy().assign(k=1), df_pois.copy().assign(k=1), on='k', suffixes=('1', '2')).drop('k', axis=1)
    
    # Application of the get_lat_lon_dist function defined with the data from the points of interest and the sensors. 
    # Creation of a new column "dist_NOME_DA_ENTIDADE" with the distance in km from each sensor to each point of interest
    dist['dist_NOME_DA_ENTIDADE'] = dist.apply(get_lat_lon_dist, axis=1)
    
    return dist


def return_amount_of_points_of_interest_per_sensor(distances_df, threshold):
    
    # We set a thresold distance equal to 1.5km because we consider, that given the size of the Porto region, 1.5km is a walkable distance. 
    # For each sensor, we defined the number of restaurants, hotels, shopping centers, etc that are at a distance of 1.5km or less
    dist_new = distances_df.copy()
    dist_new['is_below_threshold'] = np.where(dist_new['dist_NOME_DA_ENTIDADE'] <= threshold, 1, 0)
    
    
    # Check this later
    # sensor_categ = dist_new.groupby(['entity_id', 'category'])['is_below_threshold'].sum().reset_index()
    # sensor_categ = sensor_categ.pivot_table(index = "entity_id", columns = "category", values = "is_below_threshold")
    
    return dist_new

In [55]:
def read_shapefile(shp_path):
    """
    Read a shapefile into a Pandas dataframe with a 'coords' column holding
    the geometry information. This uses the pyshp package
    """

    #read file, parse out the records and shapes
    sf = shapefile.Reader(shp_path)
    fields = [x[0] for x in sf.fields][1:]
    records = sf.records()
    shps = [s.points for s in sf.shapes()]

    #write into a dataframe
    df = pd.DataFrame(columns=fields, data=records)
    df = df.assign(coords=shps)

    return df

In [50]:
# Read Sensor List
sensor_list = pd.read_csv('data/noise_sensor_list.csv', sep = ';')
sensor_list['Sensor_ID'] = ['C1', 'C2', 'C3', 'C4', 'C5']

sensor_list['Lat'] = sensor_list['Lat'].str.replace(',', '.').astype(float)
sensor_list['Long'] = sensor_list['Long'].str.replace(',', '.').astype(float)

sensor_list

,code,address,Lat,Long,streaming,Sensor_ID
0,s_01,"Via Saluzzo, 26 Torino",45.059172,7.678986,https://userportal.smartdatanet.it/userportal/...,C1
1,s_02,"Via Principe Tommaso, 18bis Torino",45.057837,7.681555,https://userportal.smartdatanet.it/userportal/...,C2
2,s_03,Largo Saluzzo Torino,45.058518,7.678854,https://userportal.smartdatanet.it/userportal/...,C3
3,s_05,Via Principe Tommaso angolo via Baretti Torino,45.057603,7.681348,https://userportal.smartdatanet.it/userportal/...,C4
4,s_06,"Corso Marconi, 27 Torino",45.055554,7.682590,https://userportal.smartdatanet.it/userportal/...,C5

In [51]:
final_businesses

,WKT,ADDRESS,OPEN YEAR,OPEN MONTH,TYPE,Description,Merchandise Type,Longitude,Latitude
0,POINT (1396322.217 4990301.69),VIA CLAUDIO LUIGI BERTHOLLET 24,1977,1,EXTRALIMENTARI,PICCOLE STRUTTURE,Extralimentari,7.682778,45.058444
1,POINT (1396322.217 4990301.69),VIA CLAUDIO LUIGI BERTHOLLET 24,1985,6,ALIMENTARI,PICCOLE STRUTTURE,Panificio,7.682778,45.058444
2,POINT (1396303.762 4990325.001),VIA CLAUDIO LUIGI BERTHOLLET 25/F,2017,9,ALTRO,DIA di somministrazione,Nessuna,7.682632,45.058607
3,POINT (1396434.395 4990540.6),CORSO VITTORIO EMANUELE II 21/A,2013,10,ALTRO,DIA di somministrazione,Nessuna,7.684246,45.060567
4,POINT (1396434.395 4990540.6),CORSO VITTORIO EMANUELE II 21/A,2009,2,ALTRO,DIA di somministrazione,Nessuna,7.684246,45.060567
...,...,...,...,...,...,...,...,...,...
823,POINT (1396561.148 4990473.514),CORSO VITTORIO EMANUELE II 9,2016,9,ALIMENTARI,PICCOLE STRUTTURE,217,8.401330,40.837933
824,POINT (1396561.148 4990473.514),CORSO VITTORIO EMANUELE II 9,2016,7,EXTRALIMENTARI,PICCOLE STRUTTURE,208,8.401330,40.837933
825,POINT (1396561.148 4990473.514),CORSO VITTORIO EMANUELE II 9,1993,4,EXTRALIMENTARI,PICCOLE STRUTTURE,Extralimentari,8.401330,40.837933
826,POINT (1396319.554 4990303.098),VIA CLAUDIO LUIGI BERTHOLLET 24/C,2001,12,EXTRALIMENTARI,PICCOLE STRUTTURE,Abbigliamento,7.682837,45.058413
827,POINT (1396322.217 4990301.69),VIA CLAUDIO LUIGI BERTHOLLET 24,2008,7,ALTRO,Somministrazione,Nessuna,7.682778,45.058444

In [56]:
distances = compute_distances(final_businesses, sensor_list)
distances

,code,address,Lat,Long,streaming,Sensor_ID,latitude1,longitude1,WKT,ADDRESS,OPEN YEAR,OPEN MONTH,TYPE,Description,Merchandise Type,Longitude,Latitude,latitude2,longitude2,dist_NOME_DA_ENTIDADE
0,s_01,"Via Saluzzo, 26 Torino",45.059172,7.678986,https://userportal.smartdatanet.it/userportal/...,C1,45.059172,7.678986,POINT (1396322.217 4990301.69),VIA CLAUDIO LUIGI BERTHOLLET 24,1977,1,EXTRALIMENTARI,PICCOLE STRUTTURE,Extralimentari,7.682778,45.058444,45.058444,7.682778,0.309472
1,s_01,"Via Saluzzo, 26 Torino",45.059172,7.678986,https://userportal.smartdatanet.it/userportal/...,C1,45.059172,7.678986,POINT (1396322.217 4990301.69),VIA CLAUDIO LUIGI BERTHOLLET 24,1985,6,ALIMENTARI,PICCOLE STRUTTURE,Panificio,7.682778,45.058444,45.058444,7.682778,0.309472
2,s_01,"Via Saluzzo, 26 Torino",45.059172,7.678986,https://userportal.smartdatanet.it/userportal/...,C1,45.059172,7.678986,POINT (1396303.762 4990325.001),VIA CLAUDIO LUIGI BERTHOLLET 25/F,2017,9,ALTRO,DIA di somministrazione,Nessuna,7.682632,45.058607,45.058607,7.682632,0.293933
3,s_01,"Via Saluzzo, 26 Torino",45.059172,7.678986,https://userportal.smartdatanet.it/userportal/...,C1,45.059172,7.678986,POINT (1396434.395 4990540.6),CORSO VITTORIO EMANUELE II 21/A,2013,10,ALTRO,DIA di somministrazione,Nessuna,7.684246,45.060567,45.060567,7.684246,0.442336
4,s_01,"Via Saluzzo, 26 Torino",45.059172,7.678986,https://userportal.smartdatanet.it/userportal/...,C1,45.059172,7.678986,POINT (1396434.395 4990540.6),CORSO VITTORIO EMANUELE II 21/A,2009,2,ALTRO,DIA di somministrazione,Nessuna,7.684246,45.060567,45.060567,7.684246,0.442336
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4135,s_06,"Corso Marconi, 27 Torino",45.055554,7.682590,https://userportal.smartdatanet.it/userportal/...,C5,45.055554,7.682590,POINT (1396561.148 4990473.514),CORSO VITTORIO EMANUELE II 9,2016,9,ALIMENTARI,PICCOLE STRUTTURE,217,8.401330,40.837933,40.837933,8.401330,472.194362
4136,s_06,"Corso Marconi, 27 Torino",45.055554,7.682590,https://userportal.smartdatanet.it/userportal/...,C5,45.055554,7.682590,POINT (1396561.148 4990473.514),CORSO VITTORIO EMANUELE II 9,2016,7,EXTRALIMENTARI,PICCOLE STRUTTURE,208,8.401330,40.837933,40.837933,8.401330,472.194362
4137,s_06,"Corso Marconi, 27 Torino",45.055554,7.682590,https://userportal.smartdatanet.it/userportal/...,C5,45.055554,7.682590,POINT (1396561.148 4990473.514),CORSO VITTORIO EMANUELE II 9,1993,4,EXTRALIMENTARI,PICCOLE STRUTTURE,Extralimentari,8.401330,40.837933,40.837933,8.401330,472.194362
4138,s_06,"Corso Marconi, 27 Torino",45.055554,7.682590,https://userportal.smartdatanet.it/userportal/...,C5,45.055554,7.682590,POINT (1396319.554 4990303.098),VIA CLAUDIO LUIGI BERTHOLLET 24/C,2001,12,EXTRALIMENTARI,PICCOLE STRUTTURE,Abbigliamento,7.682837,45.058413,45.058413,7.682837,0.318278
4139,s_06,"Corso Marconi, 27 Torino",45.055554,7.682590,https://userportal.smartdatanet.it/userportal/...,C5,45.055554,7.682590,POINT (1396322.217 4990301.69),VIA CLAUDIO LUIGI BERTHOLLET 24,2008,7,ALTRO,Somministrazione,Nessuna,7.682778,45.058444,45.058444,7.682778,0.321528

In [57]:
distances.to_csv("data/distances_sensors_pois.csv")

In [70]:
# mapping_location_area_code
mapping_location_area_code = pd.DataFrame(
    [['s_01', 65, 55, 'IV - Aree di intensa attività umana'],
    ['s_02', 60, 50, 'III - Aree di tipo misto'],
    ['s_03', 60, 50, 'III - Aree di tipo misto'],
    ['s_05', 65, 55, 'IV - Aree di intensa attività umana'],
    ['s_06', 60, 50, 'III - Aree di tipo misto']],
    columns=['code', 'day_max_db', 'night_max_db', 'area_type']
)


# Get different dataframes per threshold
for thresh in [0.1, 0.2, 0.3, 0.4, 0.5, 1, 1.5]:
    thresh_df = return_amount_of_points_of_interest_per_sensor(distances, thresh)
    thresh_w_mapping = thresh_df.merge(mapping_location_area_code, on=['code'])
    thresh_w_mapping.to_csv(f"data/thresh_df_{thresh}.csv")
    
thresh_w_mapping

,code,address,Lat,Long,streaming,Sensor_ID,latitude1,longitude1,WKT,ADDRESS,...,Merchandise Type,Longitude,Latitude,latitude2,longitude2,dist_NOME_DA_ENTIDADE,is_below_threshold,day_max_db,night_max_db,area_type
0,s_01,"Via Saluzzo, 26 Torino",45.059172,7.678986,https://userportal.smartdatanet.it/userportal/...,C1,45.059172,7.678986,POINT (1396322.217 4990301.69),VIA CLAUDIO LUIGI BERTHOLLET 24,...,Extralimentari,7.682778,45.058444,45.058444,7.682778,0.309472,1,65,55,IV - Aree di intensa attività umana
1,s_01,"Via Saluzzo, 26 Torino",45.059172,7.678986,https://userportal.smartdatanet.it/userportal/...,C1,45.059172,7.678986,POINT (1396322.217 4990301.69),VIA CLAUDIO LUIGI BERTHOLLET 24,...,Panificio,7.682778,45.058444,45.058444,7.682778,0.309472,1,65,55,IV - Aree di intensa attività umana
2,s_01,"Via Saluzzo, 26 Torino",45.059172,7.678986,https://userportal.smartdatanet.it/userportal/...,C1,45.059172,7.678986,POINT (1396303.762 4990325.001),VIA CLAUDIO LUIGI BERTHOLLET 25/F,...,Nessuna,7.682632,45.058607,45.058607,7.682632,0.293933,1,65,55,IV - Aree di intensa attività umana
3,s_01,"Via Saluzzo, 26 Torino",45.059172,7.678986,https://userportal.smartdatanet.it/userportal/...,C1,45.059172,7.678986,POINT (1396434.395 4990540.6),CORSO VITTORIO EMANUELE II 21/A,...,Nessuna,7.684246,45.060567,45.060567,7.684246,0.442336,1,65,55,IV - Aree di intensa attività umana
4,s_01,"Via Saluzzo, 26 Torino",45.059172,7.678986,https://userportal.smartdatanet.it/userportal/...,C1,45.059172,7.678986,POINT (1396434.395 4990540.6),CORSO VITTORIO EMANUELE II 21/A,...,Nessuna,7.684246,45.060567,45.060567,7.684246,0.442336,1,65,55,IV - Aree di intensa attività umana
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4135,s_06,"Corso Marconi, 27 Torino",45.055554,7.682590,https://userportal.smartdatanet.it/userportal/...,C5,45.055554,7.682590,POINT (1396561.148 4990473.514),CORSO VITTORIO EMANUELE II 9,...,217,8.401330,40.837933,40.837933,8.401330,472.194362,0,60,50,III - Aree di tipo misto
4136,s_06,"Corso Marconi, 27 Torino",45.055554,7.682590,https://userportal.smartdatanet.it/userportal/...,C5,45.055554,7.682590,POINT (1396561.148 4990473.514),CORSO VITTORIO EMANUELE II 9,...,208,8.401330,40.837933,40.837933,8.401330,472.194362,0,60,50,III - Aree di tipo misto
4137,s_06,"Corso Marconi, 27 Torino",45.055554,7.682590,https://userportal.smartdatanet.it/userportal/...,C5,45.055554,7.682590,POINT (1396561.148 4990473.514),CORSO VITTORIO EMANUELE II 9,...,Extralimentari,8.401330,40.837933,40.837933,8.401330,472.194362,0,60,50,III - Aree di tipo misto
4138,s_06,"Corso Marconi, 27 Torino",45.055554,7.682590,https://userportal.smartdatanet.it/userportal/...,C5,45.055554,7.682590,POINT (1396319.554 4990303.098),VIA CLAUDIO LUIGI BERTHOLLET 24/C,...,Abbigliamento,7.682837,45.058413,45.058413,7.682837,0.318278,1,60,50,III - Aree di tipo misto
4139,s_06,"Corso Marconi, 27 Torino",45.055554,7.682590,https://userportal.smartdatanet.it/userportal/...,C5,45.055554,7.682590,POINT (1396322.217 4990301.69),VIA CLAUDIO LUIGI BERTHOLLET 24,...,Nessuna,7.682778,45.058444,45.058444,7.682778,0.321528,1,60,50,III - Aree di tipo misto

In [76]:
# Group by number of counts per category
thresh_w_mapping = pd.read_csv("data/thresh_df_0.1.csv")


sensor_categ = thresh_w_mapping.groupby(['Sensor_ID', 'Merchandise Type'])['is_below_threshold'].sum().reset_index()
sensor_categ = sensor_categ.pivot_table(index = "Sensor_ID", columns = "Merchandise Type", values = "is_below_threshold")

sensor_categ

Merchandise Type,205,207,208,214,217,99,Abbigliamento,Alimentari,Alimentari annessi ad altra attivita,Articoli per animali,...,Pizza al taglio,Profumeria,Quotidiani e periodici,Ricambi auto e accessori,Sexy shop,Tabacchi,Telefonia,Tessuti,Vendita al dettaglio di cose antiche ed usate,Vendita non esclusiva di giornali
Sensor_ID,,,,,,,,,,,,,,,,,,,,,
C1,0,0,0,0,0,0,2,12,0,1,...,0,0,0,0,0,0,4,0,3,0
C2,0,0,0,0,0,0,4,0,0,0,...,0,0,1,0,0,0,0,1,2,0
C3,0,0,0,0,0,0,2,8,0,1,...,0,2,0,0,0,1,1,0,3,0
C4,0,0,0,0,0,0,3,1,0,0,...,0,0,1,0,0,0,0,1,1,0
C5,0,0,0,0,0,0,1,1,1,0,...,1,2,1,0,0,0,2,0,0,0

Index(['205', '207', '208', '214', '217', '99', 'Abbigliamento', 'Alimentari',
       'Alimentari annessi ad altra attivita', 'Articoli per animali',
       'Articoli pr la casa', 'Articoli sanitari e ortopedici', 'Audiovisivi',
       'Autoveicoli e motoveicoli', 'Bibite', 'Bigiotteria', 'Calzature',
       'Carburanti', 'Cartolerie', 'Casalinghi - Igiene casa e persona',
       'Elettrodomestici e/o ricambi', 'Elettronica', 'Enoteca',
       'Erboristeria', 'Extralimentari', 'Farmacia', 'Ferramenta',
       'Fiori e piante', 'Frutta e verdura', 'Gastronomia', 'Gelateria',
       'Giocattoli', 'Intimo', 'Librerie', 'Macelleria', 'Minimercato',
       'Mista', 'Mobili', 'Negozio con apparecchi automatici', 'Nessuna',
       'Non alimentari annessi ad altre attivita', 'Non alimentari generici',
       'Oggetti preziosi', 'Opere d'arte', 'Ottica', 'Panetteria', 'Panificio',
       'Pasticceria', 'Pescheria', 'Phone center', 'Pizza al taglio',
       'Profumeria', 'Quotidiani e periodici', 'Ricambi auto e accessori',
       'Sexy shop', 'Tabacchi', 'Telefonia', 'Tessuti',
       'Vendita al dettaglio di cose antiche ed usate',
       'Vendita non esclusiva di giornali'],
      dtype='object', name='Merchandise Type')